# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

container:
  image: cscotest.azurecr.io/mabuild:latest
  endpoint: CSCOTest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo 'Display commit hash: $(Build.SourceVersion)'
  displayName: 'Run a multi-line script'
- task: CMake@1
  inputs:
    workingDirectory: build
    cmakeArgs: ../
- task: CMake@1
  inputs:
    cmakeArgs: '--build .'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'
    Contents: 'main.hex'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '477fc493-2c12-4877-954a-3040372f2485/40809f3d-1cfb-45c7-b7e3-589968369bc9'
    vstsFeedPackagePublish: 'main.hex'
    versionOption: 'patch'
    packagePublishDescription: 'hex file output'
- script: cat /proc/cpuinfo
- script: echo $(Build.BuildId)
