# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: RunTestScript
  steps:
  - script: |
      echo Hello, world!
      echo Pipeline ID: $(system.definitionId)
- job: BuildAndPublish
  container:
    image: cscotest.azurecr.io/mabuild:latest
    endpoint: CSCOTest
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: build
      cmakeArgs: ../
  - task: CMake@1
    inputs:
      cmakeArgs: '--build .'
  - script: |
      tar -zcvf $(Build.ArtifactStagingDirectory)/AVRCommon build/main.hex
      md5sum $(Build.ArtifactStagingDirectory)/AVRCommon | cut -d ' ' -f 1 > $(Build.ArtifactStagingDirectory)/AVRCommon.md5
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'avr-common'
      publishLocation: 'pipeline'