# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - docker

pr:
  paths:
    include:
    - docker

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd78f3a82-dd05-48e9-85a5-a9cea426baf4'
  imageRepository: 'mabuild'
  containerRegistry: 'cscotest.azurecr.io'
  dockerfilePath: 'docker/Dockerfile'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
- bash: |
    VERTAG=$(grep version docker/Dockerfile | cut -d '"' -f 2)
    echo "##vso[task.setvariable variable=vertag]$VERTAG"
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '477fc493-2c12-4877-954a-3040372f2485/40809f3d-1cfb-45c7-b7e3-589968369bc9'
    vstsFeedPackage: '276eff5a-35b2-4072-a374-17ef9ba840f5'
    vstsPackageVersion: '0.0.3'
- script: |
    echo 'Checking for download'
    ls -lah $(Build.ArtifactStagingDirectory)
    md5sum $(Build.ArtifactStagingDirectory)/*
    echo 'Version tag: '$(vertag)
- task: Docker@2
  displayName: Build docker image
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    buildContext: $(Build.ArtifactStagingDirectory)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(vertag)
      latest
- task: Docker@2
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: Push image to container registry
  inputs:
    command: Push
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(vertag)
      latest