# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '477fc493-2c12-4877-954a-3040372f2485'
    definition: '2'
    buildVersionToDownload: 'latest'
    artifactName: 'avr-common'
    targetPath: '$(Build.ArtifactStagingDirectory)'
- script: |
    ls -lah $(Build.ArtifactStagingDirectory)
    cat $(Build.ArtifactStagingDirectory)/AVRCommon.md5
    md5sum $(Build.ArtifactStagingDirectory)/AVRCommon
