parameters:
- name: filename
  type: string
  default: arch
- name: verstring
  type: string
  default: 1.0.0
- name: filelist
  type: string
  default: '*'
- name: package
  type: string
  default: arch
- name: description
  type: string
  default: ''

steps:
- bash: |
    mkdir $(Build.BinariesDirectory)/${{ parameters.filename }}
    tar -zcvf $(Build.BinariesDirectory)/${{ parameters.filename }}/${{ parameters.filename }}_${{ parameters.verstring }} ${{ parameters.filelist }}
    md5sum $(Build.BinariesDirectory)/${{ parameters.filename }}/${{ parameters.filename }}_${{ parameters.verstring }} | cut -d ' ' -f 1 > $(Build.BinariesDirectory)/${{ parameters.filename }}/${{ parameters.filename }}_${{ parameters.verstring }}.md5
  name: Package
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.BinariesDirectory)/${{ parameters.filename }}'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '477fc493-2c12-4877-954a-3040372f2485/40809f3d-1cfb-45c7-b7e3-589968369bc9'
    vstsFeedPackagePublish: '${{ parameters.package }}'
    versionOption: 'custom'
    versionPublish: '${{ parameters.verstring }}'
    packagePublishDescription: '${{ parameters.description }}'